declare -A copybooks
copybooks[CLANAGRU]="NOTB0020.txt"
copybooks[CLANAREC]="Q2WRT0SH.txt"
copybooks[CLANGDEC]="Q2S650RH.txt"
copybooks[CLCANCDG]="Q2SLG0RH.txt"
copybooks[CLCLASOG]="Q2WCL0S.txt"
copybooks[CLCOLREL]="Q2WRE0S.txt"
copybooks[CLCOORDI]="Q2WCA0S.txt"
copybooks[CLDATGEN]="Q2WGD0S.txt"
copybooks[CLDATIPF]="Q2WNC0S.txt"
copybooks[CLDATNDG]="Q2WEN0S.txt"
copybooks[CLDECALE]="Q2S840RH.txt"
copybooks[CLDECODI]="Q2SDECU.txt"
copybooks[CLDISGRI]="Q2S710RH.txt"
copybooks[CLDIZDAT]="Q2S610RH.txt"
copybooks[CLDOCNDG]="Q2WDO0S.txt"
copybooks[CLDOMATE]="Q2SATEU.txt"
copybooks[CLDOMCAP]="Q2SCAPU.txt"
copybooks[CLDOMCOM]="Q2SCOMU.txt"
copybooks[CLDOMLOC]="Q2SLOCU.txt"
copybooks[CLDOMPAE]="Q2SPAEU.txt"
copybooks[CLDOMPRO]="Q2SPRVU.txt"
copybooks[CLDOMPTF]="Q2SPTFUH.txt"
copybooks[CLDOMRAE]="Q2SRAEU.txt"
copybooks[CLDOMSAE]="Q2SSAEU.txt"
copybooks[CLDOMTAE]="Q2STAEU.txt"
copybooks[CLDOMVIA]="Q2SVIAUH.txt"
copybooks[CLESTREC]="Q2WER0S.txt"
copybooks[CLGESPT2]="Q2SPS0RH.txt"
copybooks[CLGESPTF]="Q2WPT0S.txt"
copybooks[CLGRUNDG]="Q2WRG0S.txt"
copybooks[CLINDALE]="Q2WNI0SH.txt"
copybooks[CLINDIRI]="Q2WIN0S.txt"
copybooks[CLLEGFID]="Q2SFR0RH.txt"
copybooks[CLPARNDG]="Q2WPA0S.txt"
copybooks[CLRACTSO]="Q2SRFIRH.txt"
copybooks[CLRELGRD]="Q2S700RH.txt"
copybooks[CLRUONDG]="Q2WRN0S.txt"
copybooks[CLSTRDAT]="Q2S630RH.txt"
copybooks[CLUSOREC]="Q2WUR0S.txt"

for file_path in test-data/new/raw/EBCDIC/*; do
    if [[ $(basename "$file_path") == H* ]]; then
        continue
    fi
    file_name=$(basename "$file_path")
    file_base="${file_name%%.*}"
    file_ts="${file_name#*.}"
    file_ts_formatted="${file_ts:0:4}-${file_ts:4:2}-${file_ts:6:2}T${file_ts:8:2}:${file_ts:10:2}:${file_ts:12:2}"
    python3 ../src/main.py both test-data/new/raw/copybook/${copybooks[$file_base]} test-data/new/processed/copybook_json/${copybooks[$file_base]}.json -input "$file_path" -output test-data/new/processed/data/${file_base}/LOAD_TS=${file_ts_formatted}/${file_base}.parquet -print 100000
done